name: interactive_devices
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - scikit-learn
  - tqdm
  - pyserial
  - matplotlib
  - pandas
  - seaborn
  - python-dotenv
  - pip
  - pip:
      - pyautogui
      - tensorflow
      - openai
      - SpeechRecognition
      - windows-toasts; platform_system == "Windows"
      - PyQt6==6.7.1
      - pyaudio
