name: interactive_devices
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - scikit-learn
  - tqdm
  - pyserial
  - matplotlib
  - pandas
  - seaborn
  - pyqt
  - python-dotenv
  - pip
  - pip:
      - pyaudio
      - pyautogui
      - tensorflow
      - openai
      - SpeechRecognition
      - windows-toasts
